/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Pendulo.glb s
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Pendulo.glb')
  return (
    <group {...props} dispose={null} ref={props.movimiento} position={[0,17.5,0]} scale={1.6}>
      <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} scale={[0.84, 0.35, 0.84]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.003']} position={[0, -2.8, 0]} scale={0.74} />
    </group>
  )
}

useGLTF.preload('/Pendulo.glb')
