/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 Soporte.glb s
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Soporte(props) {
  const { nodes, materials } = useGLTF('/Soporte.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.AnyConvcom__Stand_N191213.geometry} material={nodes.AnyConvcom__Stand_N191213.material} position={[-0.45, 0.93, 0.3]} rotation={[0, 0.8, 0]} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/Soporte.glb')
